<?php

namespace App\Modules\HR\Providers;

use App\Modules\HR\Models\AttendanceRecord;
use App\Modules\HR\Models\Department;
use App\Modules\HR\Models\Employee;
use App\Modules\HR\Models\EmployeeLoan;
use App\Modules\HR\Models\EmployeeOnboarding;
use App\Modules\HR\Models\EmployeeTrainingRecord;
use App\Modules\HR\Models\ExpenseClaim;
use App\Modules\HR\Models\ExpenseClaimItem;
use App\Modules\HR\Models\JobApplication;
use App\Modules\HR\Models\JobPosition;
use App\Modules\HR\Models\LeaveBalance;
use App\Modules\HR\Models\LeaveRequest;
use App\Modules\HR\Models\LeaveType;
use App\Modules\HR\Models\LoanRepayment;
use App\Modules\HR\Models\OnboardingChecklist;
use App\Modules\HR\Models\OnboardingProgress;
use App\Modules\HR\Models\OnboardingTask;
use App\Modules\HR\Models\OnboardingTemplate;
use App\Modules\HR\Models\PayrollRun;
use App\Modules\HR\Models\Payslip;
use App\Modules\HR\Models\PerformanceKpi;
use App\Modules\HR\Models\PerformanceReview;
use App\Modules\HR\Models\ReviewRating;
use App\Modules\HR\Models\ShiftAssignment;
use App\Modules\HR\Models\ShiftTemplate;
use App\Modules\HR\Models\TrainingCourse;
use App\Modules\HR\Models\TrainingEnrollment;
use App\Modules\HR\Models\EmployeeCertification;
use App\Modules\HR\Models\WorkSchedule;
use App\Modules\HR\Models\DisciplinaryCase;
use App\Modules\HR\Models\Grievance;
use App\Modules\HR\Models\Timesheet;
use App\Modules\HR\Models\TimesheetEntry;
use App\Modules\HR\Policies\AttendancePolicy;
use App\Modules\HR\Policies\DepartmentPolicy;
use App\Modules\HR\Policies\EmployeeOnboardingPolicy;
use App\Modules\HR\Policies\EmployeePolicy;
use App\Modules\HR\Policies\ExpenseClaimPolicy;
use App\Modules\HR\Policies\LeavePolicy;
use App\Modules\HR\Policies\LeaveRequestPolicy;
use App\Modules\HR\Policies\LoanPolicy;
use App\Modules\HR\Policies\OnboardingPolicy;
use App\Modules\HR\Policies\OnboardingTemplatePolicy;
use App\Modules\HR\Policies\PayrollRunPolicy;
use App\Modules\HR\Policies\PayrollPolicy;
use App\Modules\HR\Policies\PerformanceReviewPolicy;
use App\Modules\HR\Policies\RecruitmentPolicy;
use App\Modules\HR\Policies\ShiftPolicy;
use App\Modules\HR\Policies\TrainingPolicy;
use App\Modules\HR\Policies\DisciplinaryPolicy;
use App\Modules\HR\Policies\TimesheetPolicy;
use App\Modules\HR\Models\BenefitPlan;
use App\Modules\HR\Models\EmployeeBenefit;
use App\Modules\HR\Policies\BenefitPolicy;
use App\Modules\HR\Models\WorkScheduleShift;
use App\Modules\HR\Models\EmployeeSchedule;
use App\Modules\HR\Policies\WorkSchedulePolicy;
use App\Modules\HR\Models\EmployeeDocument;
use App\Modules\HR\Policies\EmployeeDocumentPolicy;
use App\Modules\HR\Models\SkillDefinition;
use App\Modules\HR\Models\EmployeeSkill;
use App\Modules\HR\Policies\EmployeeSkillPolicy;
use App\Modules\HR\Models\HrAnnouncement;
use App\Modules\HR\Policies\HrAnnouncementPolicy;
use App\Modules\HR\Models\EmployeeExit;
use App\Modules\HR\Policies\EmployeeExitPolicy;
use App\Modules\HR\Models\EmployeePositionChange;
use App\Modules\HR\Policies\PositionChangePolicy;
use App\Modules\HR\Models\OvertimeRequest;
use App\Modules\HR\Policies\OvertimeRequestPolicy;
use App\Modules\HR\Models\SalaryGrade;
use App\Modules\HR\Policies\SalaryGradePolicy;
use App\Modules\HR\Models\EmployeeSurvey;
use App\Modules\HR\Models\FlexibleWorkArrangement;
use App\Modules\HR\Policies\FlexibleWorkPolicy;
use App\Modules\HR\Policies\EmployeeSurveyPolicy;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\ServiceProvider;

class HRServiceProvider extends ServiceProvider
{
    public function register(): void {}

    public function boot(): void
    {
        $this->loadRoutesFrom(__DIR__ . '/../routes/hr.php');

        Gate::policy(AttendanceRecord::class,       AttendancePolicy::class);
        Gate::policy(Department::class,              DepartmentPolicy::class);
        Gate::policy(Employee::class,                EmployeePolicy::class);
        Gate::policy(EmployeeLoan::class,            LoanPolicy::class);
        Gate::policy(EmployeeOnboarding::class,      EmployeeOnboardingPolicy::class);
        Gate::policy(ExpenseClaim::class,            ExpenseClaimPolicy::class);
        Gate::policy(ExpenseClaimItem::class,        ExpenseClaimPolicy::class);
        Gate::policy(JobApplication::class,          RecruitmentPolicy::class);
        Gate::policy(JobPosition::class,             RecruitmentPolicy::class);
        Gate::policy(LeaveBalance::class,            LeavePolicy::class);
        Gate::policy(LeaveRequest::class,            LeaveRequestPolicy::class);
        Gate::policy(LeaveType::class,               LeavePolicy::class);
        Gate::policy(LoanRepayment::class,           LoanPolicy::class);
        Gate::policy(OnboardingChecklist::class,     OnboardingPolicy::class);
        Gate::policy(OnboardingTask::class,          OnboardingPolicy::class);
        Gate::policy(OnboardingProgress::class,      OnboardingPolicy::class);
        Gate::policy(OnboardingTemplate::class,      OnboardingTemplatePolicy::class);
        Gate::policy(PayrollRun::class,              PayrollRunPolicy::class);
        Gate::policy(Payslip::class,                 PayrollPolicy::class);
        Gate::policy(PerformanceKpi::class,          PerformanceReviewPolicy::class);
        Gate::policy(ReviewRating::class,            PerformanceReviewPolicy::class);
        Gate::policy(PerformanceReview::class,       PerformanceReviewPolicy::class);
        Gate::policy(TrainingCourse::class,          TrainingPolicy::class);
        Gate::policy(TrainingEnrollment::class,   TrainingPolicy::class);
        Gate::policy(EmployeeCertification::class, TrainingPolicy::class);
        Gate::policy(EmployeeTrainingRecord::class,  TrainingPolicy::class);
        Gate::policy(ShiftTemplate::class,           ShiftPolicy::class);
        Gate::policy(ShiftAssignment::class,         ShiftPolicy::class);
        Gate::policy(DisciplinaryCase::class,        DisciplinaryPolicy::class);
        Gate::policy(Grievance::class,               DisciplinaryPolicy::class);
        Gate::policy(Timesheet::class,               TimesheetPolicy::class);
        Gate::policy(TimesheetEntry::class,          TimesheetPolicy::class);
        Gate::policy(BenefitPlan::class,     BenefitPolicy::class);
        Gate::policy(EmployeeBenefit::class,  BenefitPolicy::class);
        Gate::policy(WorkSchedule::class,          WorkSchedulePolicy::class);
        Gate::policy(WorkScheduleShift::class,     WorkSchedulePolicy::class);
        Gate::policy(EmployeeSchedule::class,      WorkSchedulePolicy::class);
        Gate::policy(EmployeeDocument::class,      EmployeeDocumentPolicy::class);
        Gate::policy(SkillDefinition::class,       EmployeeSkillPolicy::class);
        Gate::policy(EmployeeSkill::class,         EmployeeSkillPolicy::class);
        Gate::policy(HrAnnouncement::class,          HrAnnouncementPolicy::class);
        Gate::policy(EmployeeExit::class,            EmployeeExitPolicy::class);
        Gate::policy(EmployeePositionChange::class,  PositionChangePolicy::class);
        Gate::policy(SalaryGrade::class,             SalaryGradePolicy::class);
        Gate::policy(OvertimeRequest::class,         OvertimeRequestPolicy::class);
        Gate::policy(EmployeeSurvey::class,          EmployeeSurveyPolicy::class);
        Gate::policy(FlexibleWorkArrangement::class,  FlexibleWorkPolicy::class);
    }
}